import { getExerciseUiCopy, getUiFamily } from '../app/ui-language.js?v=4';
import { clearSavedProgress } from '../app/state.js?v=58';

const COPY = {
  en:{title:'About SpeakUP',intro:'SpeakUP is a low-pressure language-learning prototype for practical words, speaking, stories and real-life communication.',learning:'Learning support',learningText:'SpeakUP supports language practice and confidence. It is not therapy, medical advice or an emergency service.',data:'Your data',dataText:'Your language choices and learning progress are stored in this browser on this device. SpeakUP does not require an account and does not send this progress to a SpeakUP server.',mic:'Microphone',micText:'Speaking exercises use your browser’s speech-recognition service only after you tap the microphone button. Depending on your browser or device, audio may be processed by its provider. You can use the rest of SpeakUP without microphone access.',pilot:'Pilot status',pilotText:'This is a prototype being prepared for structured user testing. Learning outcomes and wellbeing benefits have not yet been independently validated.'},
  de:{title:'Über SpeakUP',intro:'SpeakUP ist ein druckarmer Sprachlern-Prototyp für praktische Wörter, Sprechen, Geschichten und Kommunikation im echten Leben.',learning:'Unterstützung beim Lernen',learningText:'SpeakUP unterstützt Sprachpraxis und Selbstvertrauen. Es ist keine Therapie, keine medizinische Beratung und kein Notfalldienst.',data:'Deine Daten',dataText:'Deine Sprachauswahl und dein Lernfortschritt werden in diesem Browser auf diesem Gerät gespeichert. SpeakUP benötigt kein Konto und sendet diesen Fortschritt nicht an einen SpeakUP-Server.',mic:'Mikrofon',micText:'Sprechübungen nutzen den Spracherkennungsdienst deines Browsers erst, wenn du die Mikrofontaste drückst. Je nach Browser oder Gerät kann Audio durch dessen Anbieter verarbeitet werden. Den Rest von SpeakUP kannst du ohne Mikrofonzugriff verwenden.',pilot:'Pilotstatus',pilotText:'Dies ist ein Prototyp, der für strukturierte Nutzertests vorbereitet wird. Lernergebnisse und positive Auswirkungen auf das Wohlbefinden wurden noch nicht unabhängig bestätigt.'},
  pt:{title:'Sobre o SpeakUP',intro:'O SpeakUP é um protótipo de aprendizagem de línguas sem pressão, com palavras práticas, fala, histórias e comunicação da vida real.',learning:'Apoio à aprendizagem',learningText:'O SpeakUP apoia a prática da língua e a confiança. Não é terapia, aconselhamento médico nem um serviço de emergência.',data:'Os teus dados',dataText:'As tuas escolhas de língua e o progresso ficam guardados neste navegador, neste dispositivo. O SpeakUP não exige uma conta e não envia este progresso para um servidor do SpeakUP.',mic:'Microfone',micText:'Os exercícios de fala usam o serviço de reconhecimento de voz do teu navegador apenas depois de tocares no botão do microfone. Dependendo do navegador ou dispositivo, o áudio pode ser processado pelo respetivo fornecedor. Podes usar o resto do SpeakUP sem acesso ao microfone.',pilot:'Estado do piloto',pilotText:'Este é um protótipo em preparação para testes estruturados com utilizadores. Os resultados de aprendizagem e os benefícios para o bem-estar ainda não foram validados de forma independente.'},
  es:{title:'Sobre SpeakUP',intro:'SpeakUP es un prototipo de aprendizaje de idiomas sin presión, con palabras prácticas, conversación, historias y comunicación de la vida real.',learning:'Apoyo al aprendizaje',learningText:'SpeakUP apoya la práctica del idioma y la confianza. No es terapia, asesoramiento médico ni un servicio de emergencia.',data:'Tus datos',dataText:'Tus idiomas y tu progreso se guardan en este navegador y dispositivo. SpeakUP no exige una cuenta ni envía ese progreso a un servidor de SpeakUP.',mic:'Micrófono',micText:'Los ejercicios de conversación usan el reconocimiento de voz de tu navegador solo después de pulsar el micrófono. Según el navegador o dispositivo, su proveedor puede procesar el audio. Puedes usar el resto de SpeakUP sin acceso al micrófono.',pilot:'Estado del piloto',pilotText:'Este prototipo se está preparando para pruebas estructuradas con usuarios. Los resultados de aprendizaje y los beneficios para el bienestar aún no se han validado de forma independiente.'},
  hr:{title:'O SpeakUP-u',intro:'SpeakUP je prototip za opušteno učenje jezika kroz praktične riječi, govor, priče i komunikaciju iz stvarnog života.',learning:'Podrška učenju',learningText:'SpeakUP podržava vježbanje jezika i samopouzdanje. Nije terapija, medicinski savjet ni hitna služba.',data:'Tvoji podaci',dataText:'Odabir jezika i napredak spremaju se u ovom pregledniku na ovom uređaju. SpeakUP ne zahtijeva račun i ne šalje taj napredak na SpeakUP poslužitelj.',mic:'Mikrofon',micText:'Govorne vježbe koriste prepoznavanje govora preglednika tek nakon dodira gumba mikrofona. Ovisno o pregledniku ili uređaju, zvuk može obrađivati njegov pružatelj usluge. Ostatak SpeakUP-a možeš koristiti bez pristupa mikrofonu.',pilot:'Status pilot-projekta',pilotText:'Ovo je prototip koji se priprema za strukturirano testiranje s korisnicima. Ishodi učenja i koristi za dobrobit još nisu neovisno potvrđeni.'},
  fr:{title:'À propos de SpeakUP',intro:'SpeakUP est un prototype d’apprentissage des langues sans pression, fondé sur des mots pratiques, l’expression orale, des histoires et la communication réelle.',learning:'Aide à l’apprentissage',learningText:'SpeakUP soutient la pratique linguistique et la confiance. Ce n’est ni une thérapie, ni un conseil médical, ni un service d’urgence.',data:'Tes données',dataText:'Tes choix de langue et ta progression sont enregistrés dans ce navigateur, sur cet appareil. SpeakUP ne demande aucun compte et n’envoie pas cette progression à un serveur SpeakUP.',mic:'Microphone',micText:'Les exercices oraux utilisent le service de reconnaissance vocale du navigateur uniquement après ton appui sur le bouton du microphone. Selon le navigateur ou l’appareil, le son peut être traité par son fournisseur. Tu peux utiliser le reste de SpeakUP sans accès au microphone.',pilot:'État du pilote',pilotText:'Ce prototype est en préparation pour des tests structurés avec des utilisateurs. Les résultats d’apprentissage et les bénéfices pour le bien-être n’ont pas encore été validés de manière indépendante.'}
};

const CLEAR = {
  en:['Delete learning data','Delete the language choices and learning progress saved on this device?'],
  de:['Lerndaten löschen','Sprachauswahl und Lernfortschritt löschen, die auf diesem Gerät gespeichert sind?'],
  pt:['Apagar dados de aprendizagem','Apagar as escolhas de língua e o progresso guardados neste dispositivo?'],
  es:['Eliminar datos de aprendizaje','¿Eliminar los idiomas y el progreso guardados en este dispositivo?'],
  hr:['Izbriši podatke o učenju','Izbrisati odabir jezika i napredak spremljen na ovom uređaju?'],
  fr:['Supprimer les données d’apprentissage','Supprimer les langues et la progression enregistrées sur cet appareil ?']
};

export function renderAbout(root, store) {
  const state=store.getState();
  const ui=getExerciseUiCopy(state.nativeLanguage);
  const family=getUiFamily(state.nativeLanguage);
  const copy=COPY[family] || COPY.en;
  const [clearLabel,confirmText]=CLEAR[family] || CLEAR.en;
  root.innerHTML=`<section class="screen about-screen"><button class="menu-button" data-back aria-label="${ui.back}">←</button><div class="about-view"><p class="kicker">SpeakUP</p><h1>${copy.title}</h1><p class="about-intro">${copy.intro}</p><div class="about-grid"><article><h2>${copy.learning}</h2><p>${copy.learningText}</p></article><article><h2>${copy.data}</h2><p>${copy.dataText}</p></article><article><h2>${copy.mic}</h2><p>${copy.micText}</p></article><article><h2>${copy.pilot}</h2><p>${copy.pilotText}</p></article></div><button class="secondary-button about-clear" data-clear>${clearLabel}</button></div></section>`;
  root.querySelector('[data-back]').onclick=()=>store.setState({screen:'menu'});
  root.querySelector('[data-clear]').onclick=()=>{if(window.confirm(confirmText)){clearSavedProgress();window.location.reload();}};
}
