import { getMultilingualStory } from '../data/stories/multilingual-stories.js?v=1';
import { fantasyStory } from '../data/stories/fantasy.js?v=3';
import { getFantasyTranslation } from '../data/stories/fantasy-translations.js?v=1';
import { speak, stopSpeech } from '../audio/speech.js?v=63';
import { isStorySfxPlaying, preloadStorySfx, playStorySfx, stopStorySfx } from '../audio/story-sfx.js?v=31';
import { getSpeechLanguage, languageName } from '../data/language-content-matrix.js?v=1';

const PHASES=['native','learning','gap','review'];
const CHURCH_BELL_PAGES=new Set([4,5,6,7]);
const escapeHtml=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const shuffle=items=>[...items].sort(()=>Math.random()-.5);
function learningItems(text,nativeText){const clean=value=>String(value||'').replace(/[“”"'.,!?;:()—–]/g,' ').split(/\s+/).filter(word=>word.length>=4);const words=[...new Set(clean(text))].slice(0,3);const hints=clean(nativeText);while(words.length<3)words.push(clean(text)[words.length]||'story');return words.map((answer,index)=>({answer,hint:hints[index]||answer}));}
function getStory(storyId,learningLanguage,nativeLanguage){if(storyId!=='fantasy-1')return getMultilingualStory(storyId,learningLanguage,nativeLanguage);return{id:fantasyStory.id,emoji:fantasyStory.emoji,title:fantasyStory.title,subtitle:fantasyStory.subtitle,pages:fantasyStory.pages.map((source,index)=>{const learning=getFantasyTranslation(source,index,learningLanguage);const native=getFantasyTranslation(source,index,nativeLanguage);const sound=index===1?'warning-bell':CHURCH_BELL_PAGES.has(index)?'bell':source.sound;return{learning,native,sound,items:learningItems(learning,native)};})};}
function gapHtml(page,solved){let html=escapeHtml(page.learning);page.items.forEach((item,index)=>{const replacement=index<solved?`<span class="story-gap-solved">${escapeHtml(item.answer)}</span>`:`<span class="story-gap-english">${escapeHtml(item.hint)}</span>`;html=html.replace(new RegExp(`\\b${item.answer.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\b`,'i'),replacement);});return html;}
export function renderStory(root,store){const state=store.getState();const storyId=state.selectedStory||'everyday';const progressKey=[storyId,state.learningLanguage,state.nativeLanguage].join('|');const story=getStory(storyId,state.learningLanguage,state.nativeLanguage);const learningVoice=getSpeechLanguage(state.learningLanguage);const nativeVoice=getSpeechLanguage(state.nativeLanguage);const saved=state.progress?.story?.[progressKey];let pageIndex=Math.min(Math.max(Number(saved?.pageIndex)||0,0),story.pages.length-1);let phaseIndex=Math.min(Math.max(Number(saved?.phaseIndex)||0,0),PHASES.length-1);let solved=Math.max(Number(saved?.solved)||0,0);let locked=false;let renderToken=0;const page=()=>story.pages[pageIndex];const saveProgress=()=>store.updateProgress('story',progressKey,{storyId,learningLanguage:state.learningLanguage,nativeLanguage:state.nativeLanguage,pageIndex,phaseIndex,solved});
const stopNarrator=()=>stopSpeech();const stopAmbience=()=>stopStorySfx();const stopAll=()=>{stopNarrator();stopAmbience();};const leave=()=>{renderToken+=1;stopAll();store.setState({screen:'menu'});};
function shell(content){const atStart=pageIndex===0&&phaseIndex===0;const atEnd=pageIndex===story.pages.length-1&&phaseIndex===PHASES.length-1;root.innerHTML=`<section class="screen story-screen"><button class="menu-button" data-menu>Menu</button><div class="center story-view"><p class="kicker">Story Mode · ${escapeHtml(languageName(state.learningLanguage))}</p><h1>${story.emoji} ${escapeHtml(story.title)}</h1><p class="story-subtitle">${escapeHtml(story.subtitle)}</p><p class="story-progress">Page ${pageIndex+1} / ${story.pages.length} · Step ${phaseIndex+1} / ${PHASES.length}</p>${content}<nav class="story-page-nav" aria-label="Story navigation"><button class="story-nav-button" data-prev aria-label="Previous" ${atStart?'disabled':''}><span aria-hidden="true">◁</span></button><button class="story-nav-button story-nav-button-next" data-next aria-label="Next" ${atEnd?'disabled':''}><span aria-hidden="true">▷</span></button></nav></div></section>`;root.querySelector('[data-menu]').onclick=leave;root.querySelector('[data-prev]').onclick=()=>navigate(-1);root.querySelector('[data-next]').onclick=()=>navigate(1);}
function ensureAmbience(current,audioEnabled,token){if(storyId!=='fantasy-1'||!audioEnabled||!current.sound||current.sound==='none')return;if(isStorySfxPlaying(current.sound))return;const start=()=>{if(token!==renderToken)return;const live=page();if(live!==current||isStorySfxPlaying(current.sound))return;const volume=current.sound==='rain'?0.40:current.sound==='bell'?0.90:current.sound==='warning-bell'?0.55:0.30;void playStorySfx(current.sound,{enabled:true,loop:current.sound==='rain',volume});};if(current.sound==='rain'||current.sound==='bell'||current.sound==='warning-bell'){start();return;}void preloadStorySfx(current.sound).then(ok=>{if(ok)start();});}
async function narrate(text,voice,audioEnabled,rate,token){if(token!==renderToken)return;await speak(text,voice,{enabled:audioEnabled,rate});}
async function renderPhase(){const token=++renderToken;const current=page();const audioEnabled=Boolean(store.getState().audioOn);if(phaseIndex===0){ensureAmbience(current,audioEnabled,token);shell(`<p class="story-phase-label">${escapeHtml(languageName(state.nativeLanguage))}</p><p class="story-copy">${escapeHtml(current.native)}</p>`);await narrate(current.native,nativeVoice,audioEnabled,.88,token);}else if(phaseIndex===1){ensureAmbience(current,audioEnabled,token);shell(`<p class="story-phase-label">${escapeHtml(languageName(state.learningLanguage))}</p><p class="story-copy story-portuguese-copy">${escapeHtml(current.learning)}</p>`);await narrate(current.learning,learningVoice,audioEnabled,.62,token);}else if(phaseIndex===2){if(current.sound!=='rain')stopAmbience();solved=Math.min(solved,current.items.length);const item=current.items[solved];const options=shuffle(current.items.map(entry=>entry.answer));shell(`<p class="story-phase-label">Complete the story</p><p class="story-copy story-gap-copy">${gapHtml(current,solved)}</p>${item?`<div class="story-word-options">${options.map(option=>`<button class="story-word-option" data-option="${escapeHtml(option)}">${escapeHtml(option)}</button>`).join('')}</div>`:'<p class="feedback">All learning words found.</p>'}`);root.querySelectorAll('[data-option]').forEach(button=>button.onclick=()=>{if(locked)return;if(button.dataset.option.toLocaleLowerCase()===item.answer.toLocaleLowerCase()){locked=true;solved+=1;saveProgress();}else{button.classList.add('is-wrong');setTimeout(()=>button.classList.remove('is-wrong'),420);}});}else{if(current.sound!=='rain')stopAmbience();shell(`<p class="story-phase-label">Review</p><p class="story-copy story-portuguese-copy">${escapeHtml(current.learning)}</p><p class="story-copy translated">${escapeHtml(current.native)}</p>`);await narrate(current.learning,learningVoice,audioEnabled,.62,token);}}
function navigate(direction){renderToken+=1;stopNarrator();const currentSound=page().sound;const keepRain=currentSound==='rain';if(direction>0){if(phaseIndex===2&&solved<page().items.length){if(!keepRain)stopAmbience();return;}if(phaseIndex<3){if(!keepRain)stopAmbience();phaseIndex+=1;if(phaseIndex===2)solved=0;return saveProgress();}if(pageIndex<story.pages.length-1){stopAmbience();pageIndex+=1;phaseIndex=0;solved=0;return saveProgress();}}else{if(phaseIndex>0){if(!keepRain)stopAmbience();phaseIndex-=1;if(phaseIndex===2)solved=0;return saveProgress();}if(pageIndex>0){stopAmbience();pageIndex-=1;phaseIndex=3;solved=0;return saveProgress();}}}
renderPhase();}