import { VOICE_CATEGORIES } from './index.js?v=2';

const CONTEXTS = {
  'pt-PT':['','Hoje, ','Neste momento, ','Com calma, ','Passo a passo, '],
  'de-DE':['','Heute: ','In diesem Moment: ','Ganz in Ruhe: ','Schritt für Schritt: '],
  'en-GB':['','Today, ','In this moment, ','Calmly, ','Step by step, '],
  'es-ES':['','Hoy, ','En este momento, ','Con calma, ','Paso a paso, '],
  'es-AN':['','Hoy, ','Ahora mismo, ','Con calma, ','Pasito a pasito, '],
  'hr-HR':['','Danas, ','U ovom trenutku, ','Mirno, ','Korak po korak, '],
  'hr-DAL':['','Danas, ','Sad, ','Pomalo, ','Korak po korak, '],
  'fr-FR':['','Aujourd’hui, ','En ce moment, ','Doucement, ','Pas à pas, ']
};

const L = {
  'self-love': {
    'de-DE':['Ich akzeptiere mich, wie ich bin.','Ich behandle mich freundlich.','Ich respektiere meine Grenzen.','Ich erkenne meinen Wert an.','Meine Bedürfnisse dürfen Raum haben.','Ich bin stolz auf meinen Weg.','Ich darf unvollkommen und ganz sein.','Ich spreche respektvoll mit mir.','Ich verdiene Ruhe und Fürsorge.','Ich muss meinen Wert nicht beweisen.'],
    'es-ES':['Me acepto tal como soy.','Me trato con cariño.','Respeto mis límites.','Reconozco mi valor.','Doy espacio a mis necesidades.','Estoy orgullosa de mi camino.','Puedo ser imperfecta y estar completa.','Me hablo con respeto.','Merezco descanso y cuidado.','No tengo que demostrar mi valor.'],
    'hr-HR':['Prihvaćam se kakva jesam.','Odnosim se prema sebi nježno.','Poštujem svoje granice.','Prepoznajem svoju vrijednost.','Dajem prostor svojim potrebama.','Ponosna sam na svoj put.','Mogu biti nesavršena i cjelovita.','Razgovaram sa sobom s poštovanjem.','Zaslužujem odmor i brigu.','Ne moram dokazivati svoju vrijednost.'],
    'fr-FR':['Je m’accepte comme je suis.','Je me traite avec douceur.','Je respecte mes limites.','Je reconnais ma valeur.','Je fais de la place à mes besoins.','Je suis fière de mon parcours.','Je peux être imparfaite et entière.','Je me parle avec respect.','Je mérite du repos et de l’attention.','Je n’ai pas besoin de prouver ma valeur.']},
  confidence:{
    'de-DE':['Ich vertraue meiner Fähigkeit zu lernen.','Ich darf anfangen, bevor ich mich bereit fühle.','Meine Stimme verdient Raum.','Ich lerne aus jedem Versuch.','Ich kann auch mit Nervosität sprechen.','Ich habe Mut, es noch einmal zu versuchen.','Ich muss nicht perfekt sein, um weiterzugehen.','Ich erkenne an, was ich schon kann.','Ich darf meinen Platz einnehmen.','Mit jeder Übung wachse ich.'],
    'es-ES':['Confío en mi capacidad para aprender.','Puedo empezar antes de sentirme preparada.','Mi voz merece espacio.','Aprendo con cada intento.','Puedo hablar aunque esté nerviosa.','Tengo valor para intentarlo otra vez.','No necesito ser perfecta para avanzar.','Reconozco lo que ya sé.','Puedo ocupar mi lugar.','Crezco cada vez que practico.'],
    'hr-HR':['Vjerujem u svoju sposobnost učenja.','Mogu početi prije nego što se osjećam spremno.','Moj glas zaslužuje prostor.','Učim iz svakog pokušaja.','Mogu govoriti i kad sam nervozna.','Imam hrabrosti pokušati ponovno.','Ne moram biti savršena da bih napredovala.','Prepoznajem ono što već znam.','Mogu zauzeti svoje mjesto.','Rastem svaki put kad vježbam.'],
    'fr-FR':['J’ai confiance en ma capacité d’apprendre.','Je peux commencer avant de me sentir prête.','Ma voix mérite sa place.','J’apprends à chaque tentative.','Je peux parler même avec un peu de nervosité.','J’ai le courage de réessayer.','Je n’ai pas besoin d’être parfaite pour avancer.','Je reconnais ce que je sais déjà.','Je peux prendre ma place.','Je grandis chaque fois que je pratique.']},
  kindness:{
    'de-DE':['Ich entscheide mich für freundliche Worte.','Ich kann zuhören, bevor ich antworte.','Eine kleine Geste kann helfen.','Ich behandle andere mit Respekt.','Auch ich verdiene meine eigene Freundlichkeit.','Ich kann widersprechen, ohne zu verletzen.','Ich gebe Raum, wenn jemand ihn braucht.','Meine Worte können beruhigen.','Ich kann mich ehrlich entschuldigen.','Freundlichkeit macht mich nicht schwach.'],
    'es-ES':['Elijo hablar con amabilidad.','Puedo escuchar antes de responder.','Un gesto pequeño puede ayudar.','Trato a los demás con respeto.','Yo también merezco mi propia bondad.','Puedo discrepar sin hacer daño.','Doy espacio a quien lo necesita.','Mis palabras pueden calmar.','Puedo pedir perdón con sinceridad.','La amabilidad no me hace débil.'],
    'hr-HR':['Biram govoriti ljubazno.','Mogu slušati prije nego što odgovorim.','Mala gesta može pomoći.','Prema drugima se odnosim s poštovanjem.','I ja zaslužujem vlastitu dobrotu.','Mogu se ne slagati bez povređivanja.','Dajem prostor onome kome treba.','Moje riječi mogu umiriti.','Mogu se iskreno ispričati.','Ljubaznost me ne čini slabom.'],
    'fr-FR':['Je choisis de parler avec gentillesse.','Je peux écouter avant de répondre.','Un petit geste peut aider.','Je traite les autres avec respect.','Je mérite aussi ma propre gentillesse.','Je peux ne pas être d’accord sans blesser.','Je laisse de l’espace à ceux qui en ont besoin.','Mes mots peuvent apaiser.','Je peux présenter des excuses sincères.','La gentillesse ne me rend pas faible.']},
  gratitude:{
    'de-DE':['Ich bemerke heute etwas Gutes.','Ich würdige, was mich unterstützt hat.','Ich schätze kleine Momente.','Ich erkenne meine Anstrengung an.','Ich danke meinem Körper, dass er mich trägt.','Ich bewahre eine tröstliche Erinnerung.','Dankbarkeit löscht Schmerz nicht aus.','Ich sehe, wer für mich da war.','Etwas Einfaches darf mir Trost geben.','Ich erlaube mir, diesen Moment zu schätzen.'],
    'es-ES':['Noto algo bueno de este día.','Agradezco lo que me ha sostenido hoy.','Valoro los pequeños momentos.','Reconozco el esfuerzo que he hecho.','Agradezco a mi cuerpo que me acompañe.','Guardo un recuerdo que me hace bien.','La gratitud no borra el dolor.','Veo quién ha estado presente.','Algo sencillo puede darme consuelo.','Me permito apreciar este instante.'],
    'hr-HR':['Primjećujem nešto dobro u ovom danu.','Zahvalna sam na onome što me danas podržalo.','Cijenim male trenutke.','Priznajem trud koji sam uložila.','Zahvaljujem svom tijelu što me nosi.','Čuvam uspomenu koja mi donosi utjehu.','Zahvalnost ne briše bol.','Primjećujem tko je bio uz mene.','Nešto jednostavno može mi pružiti utjehu.','Dopuštam si cijeniti ovaj trenutak.'],
    'fr-FR':['Je remarque une bonne chose dans cette journée.','J’apprécie ce qui m’a soutenue aujourd’hui.','J’accorde de la valeur aux petits moments.','Je reconnais les efforts que j’ai faits.','Je remercie mon corps de m’accompagner.','Je garde un souvenir qui me réconforte.','La gratitude n’efface pas la douleur.','Je remarque qui a été présent pour moi.','Quelque chose de simple peut me réconforter.','Je m’autorise à apprécier cet instant.']},
  calm:{
    'de-DE':['Ich atme langsam und bleibe hier.','Ich darf für einen Moment langsamer werden.','Ich entspanne Schultern und Hände.','Ich muss nicht alles jetzt lösen.','Ich kehre zu dem zurück, was vor mir liegt.','Ich gehe Schritt für Schritt.','Ich darf ohne Schuldgefühl pausieren.','Stille darf Raum schaffen.','Mein Körper darf langsamer werden.','Dieser Moment braucht keine Eile.'],
    'es-ES':['Respiro despacio y me quedo aquí.','Puedo bajar el ritmo un momento.','Relajo los hombros y las manos.','No tengo que resolverlo todo ahora.','Vuelvo a lo que tengo delante.','Voy paso a paso.','Puedo parar sin sentir culpa.','Dejo que el silencio cree espacio.','Mi cuerpo puede ir más despacio.','Este momento no necesita prisa.'],
    'hr-HR':['Dišem polako i ostajem ovdje.','Mogu usporiti na trenutak.','Opuštam ramena i ruke.','Ne moram sada sve riješiti.','Vraćam se onome što je ispred mene.','Idem korak po korak.','Mogu zastati bez krivnje.','Dopuštam tišini da stvori prostor.','Moje tijelo može usporiti.','Ovaj trenutak ne treba žurbu.'],
    'fr-FR':['Je respire doucement et je reste ici.','Je peux ralentir un moment.','Je détends mes épaules et mes mains.','Je n’ai pas besoin de tout résoudre maintenant.','Je reviens à ce qui est devant moi.','J’avance pas à pas.','Je peux faire une pause sans culpabiliser.','Je laisse le silence créer de l’espace.','Mon corps peut ralentir.','Ce moment n’a pas besoin d’urgence.']},
  forgiveness:{
    'de-DE':['Ich kann den Schmerz anerkennen, ohne in ihm gefangen zu bleiben.','Vergeben bedeutet nicht vergessen.','Ich kann mich schützen und trotzdem weitergehen.','Ich lasse das Gewicht nach und nach los.','Ich muss Vergebung nicht beschleunigen.','Ich kann mir verzeihen, dass ich es nicht besser wusste.','Ich lerne, ohne mich zu bestrafen.','Eine Grenze kann auch Liebe sein.','Mein Herz darf in seinem Tempo heilen.','Weitergehen löscht das Geschehene nicht aus.'],
    'es-ES':['Puedo reconocer el dolor sin quedarme atrapada en él.','Perdonar no significa olvidar.','Puedo protegerme y seguir adelante.','Suelto el peso poco a poco.','No tengo que apresurar el perdón.','Puedo perdonarme por no haberlo sabido antes.','Aprendo sin castigarme.','Un límite también puede ser amor.','Mi corazón puede sanar a su ritmo.','Seguir adelante no borra lo ocurrido.'],
    'hr-HR':['Mogu priznati bol bez ostajanja zarobljena u njoj.','Oprostiti ne znači zaboraviti.','Mogu se zaštititi i ipak nastaviti dalje.','Otpuštam teret malo po malo.','Ne moram žuriti s oprostom.','Mogu si oprostiti što nisam znala bolje.','Učim bez kažnjavanja sebe.','Granica može biti i ljubav.','Moje srce može zacjeljivati svojim ritmom.','Kretanje dalje ne briše ono što se dogodilo.'],
    'fr-FR':['Je peux reconnaître la douleur sans y rester enfermée.','Pardonner ne signifie pas oublier.','Je peux me protéger et continuer d’avancer.','Je relâche le poids petit à petit.','Je n’ai pas besoin de précipiter le pardon.','Je peux me pardonner de ne pas avoir su mieux.','J’apprends sans me punir.','Une limite peut aussi être une forme d’amour.','Mon cœur peut guérir à son rythme.','Avancer n’efface pas ce qui s’est passé.']},
  hope:{
    'de-DE':['Es kann noch eine Möglichkeit geben.','Ein kleiner Schritt kann den Weg verändern.','Ich muss nicht den ganzen Weg sehen.','Ich lasse Raum für eine gute Überraschung.','Meine Geschichte geht weiter.','Manche Tage beginnen neu.','Eine Schwierigkeit entscheidet nicht alles.','Ich darf nach einem kleinen Licht suchen.','Die Zukunft ist noch nicht geschlossen.','Ich gehe weiter, auch ohne alle Antworten.'],
    'es-ES':['Todavía puede existir una posibilidad.','Un pequeño paso puede cambiar el camino.','No necesito ver todo el camino.','Puedo dejar espacio para una buena sorpresa.','Mi historia sigue adelante.','Hay días que empiezan de nuevo.','Una dificultad no lo decide todo.','Puedo buscar una pequeña luz.','El futuro aún no está cerrado.','Continúo aunque no tenga todas las respuestas.'],
    'hr-HR':['Još uvijek može postojati mogućnost.','Mali korak može promijeniti put.','Ne moram vidjeti cijeli put.','Mogu ostaviti prostor za dobro iznenađenje.','Moja priča se nastavlja.','Neki dani počinju iznova.','Jedna poteškoća ne odlučuje o svemu.','Mogu tražiti malo svjetla.','Budućnost još nije zatvorena.','Nastavljam i bez svih odgovora.'],
    'fr-FR':['Une possibilité peut encore exister.','Un petit pas peut changer le chemin.','Je n’ai pas besoin de voir tout le chemin.','Je peux laisser de la place à une bonne surprise.','Mon histoire continue.','Certains jours recommencent.','Une difficulté ne décide pas de tout.','Je peux chercher une petite lumière.','L’avenir n’est pas encore fermé.','Je continue même sans avoir toutes les réponses.']},
  courage:{
    'de-DE':['Ich kann handeln, auch wenn ich Angst habe.','Mut kann leise sein.','Ich mache den nächsten Schritt vorsichtig.','Ich kann sagen, was ich brauche.','Ich schütze, was mir wichtig ist.','Ich kann es auch ohne Garantie versuchen.','Nach einem Sturz kann ich wieder aufstehen.','Meine Anwesenheit ist bereits eine Form von Mut.','Ich kann eine andere Antwort wählen.','Ich muss nicht furchtlos sein, um mutig zu sein.'],
    'es-ES':['Puedo actuar aunque tenga miedo.','El valor puede ser silencioso.','Doy el siguiente paso con cuidado.','Puedo decir lo que necesito.','Protejo lo que es importante para mí.','Puedo intentarlo sin garantías.','Me levanto después de una caída.','Mi presencia ya es una forma de valor.','Puedo elegir una respuesta diferente.','No necesito no tener miedo para ser valiente.'],
    'hr-HR':['Mogu djelovati i kad osjećam strah.','Hrabrost može biti tiha.','Pažljivo činim sljedeći korak.','Mogu reći što mi treba.','Štitim ono što mi je važno.','Mogu pokušati bez jamstava.','Mogu ustati nakon pada.','Moja prisutnost već je oblik hrabrosti.','Mogu izabrati drugačiji odgovor.','Ne moram biti bez straha da bih bila hrabra.'],
    'fr-FR':['Je peux agir même avec la peur.','Le courage peut être silencieux.','Je fais le prochain pas avec prudence.','Je peux dire ce dont j’ai besoin.','Je protège ce qui compte pour moi.','Je peux essayer sans garantie.','Je me relève après une chute.','Ma présence est déjà une forme de courage.','Je peux choisir une réponse différente.','Je n’ai pas besoin d’être sans peur pour être courageuse.']},
  'stoic-wisdom':{
    'de-DE':['Ich konzentriere mich auf das, was ich kontrollieren kann.','Ich lasse los, was nicht von mir abhängt.','Meine Reaktion bleibt eine Entscheidung.','Ich muss nicht mit jedem Gedanken diskutieren.','Ich akzeptiere den Moment, bevor ich den nächsten Schritt wähle.','Eine Schwierigkeit kann mich etwas lehren.','Unbehagen entscheidet nicht, wer ich bin.','Auch an einem schweren Tag kann ich meinen Werten folgen.','Ich mache die nächste einfache Sache gut.','Frieden wächst, wenn ich das Unmögliche loslasse.'],
    'es-ES':['Me concentro en lo que puedo controlar.','Dejo pasar lo que no depende de mí.','Mi respuesta sigue siendo una elección.','No necesito discutir con cada pensamiento.','Acepto el momento antes de decidir el siguiente paso.','Una dificultad puede enseñarme algo.','La incomodidad no decide quién soy.','Puedo mantener mis valores en un día difícil.','Hago bien la siguiente cosa sencilla.','La paz crece cuando suelto lo imposible.'],
    'hr-HR':['Usredotočujem se na ono što mogu kontrolirati.','Puštam ono što ne ovisi o meni.','Moj odgovor i dalje je izbor.','Ne moram raspravljati sa svakom mišlju.','Prihvaćam trenutak prije nego što odlučim sljedeći korak.','Poteškoća me može nečemu naučiti.','Nelagoda ne odlučuje tko sam.','Mogu zadržati svoje vrijednosti i u teškom danu.','Dobro činim sljedeću jednostavnu stvar.','Mir raste kada otpustim nemoguće.'],
    'fr-FR':['Je me concentre sur ce que je peux contrôler.','Je laisse passer ce qui ne dépend pas de moi.','Ma réponse reste un choix.','Je n’ai pas besoin de discuter avec chaque pensée.','J’accepte le moment avant de décider du prochain pas.','Une difficulté peut m’apprendre quelque chose.','L’inconfort ne décide pas qui je suis.','Je peux garder mes valeurs pendant une journée difficile.','Je fais bien la prochaine chose simple.','La paix grandit quand je lâche l’impossible.']},
  'spiral-thoughts':{
    'de-DE':['Ich bemerke, dass der Gedanke sich wiederholt.','Ein Gedanke ist nicht immer eine Tatsache.','Ich kehre zu dem zurück, was ich jetzt sehe.','Ich muss dieselbe Frage nicht erneut beantworten.','Ich lasse den Gedanken vorbeiziehen, ohne ihm zu folgen.','Wenn es eine Handlung gibt, kann ich sie notieren.','Wenn es keine Handlung gibt, darf ich ruhen.','Mein Gehirn ist müde, nicht kaputt.','Ich kann meine Aufmerksamkeit auf meinen Körper lenken.','Die Antwort darf nach der Ruhe kommen.'],
    'es-ES':['Noto que el pensamiento se repite.','Un pensamiento no siempre es un hecho.','Puedo volver a lo que veo ahora.','No necesito responder otra vez a la misma pregunta.','Dejo pasar el pensamiento sin seguirlo.','Si hay una acción, puedo apuntarla.','Si no hay una acción, puedo descansar.','Mi cerebro está cansado, no roto.','Puedo llevar la atención a mi cuerpo.','La respuesta puede aparecer después del descanso.'],
    'hr-HR':['Primjećujem da se misao ponavlja.','Misao nije uvijek činjenica.','Mogu se vratiti onome što sada vidim.','Ne moram ponovno odgovarati na isto pitanje.','Puštam misao da prođe bez praćenja.','Ako postoji radnja, mogu je zapisati.','Ako nema radnje, mogu se odmoriti.','Moj je mozak umoran, nije slomljen.','Mogu preusmjeriti pažnju na tijelo.','Odgovor se može pojaviti nakon odmora.'],
    'fr-FR':['Je remarque que la pensée se répète.','Une pensée n’est pas toujours un fait.','Je peux revenir à ce que je vois maintenant.','Je n’ai pas besoin de répondre encore à la même question.','Je laisse passer la pensée sans la suivre.','S’il y a une action, je peux la noter.','S’il n’y a aucune action, je peux me reposer.','Mon cerveau est fatigué, pas cassé.','Je peux ramener mon attention vers mon corps.','La réponse peut apparaître après le repos.']},
  visualisation:{
    'de-DE':['Ich stelle mir einen sicheren Ort vor.','Ich sehe den nächsten Schritt klar.','Ich stelle mir vor, eine kleine Aufgabe zu beenden.','Ich erschaffe ein einfaches Bild meines Ziels.','Ich bemerke Farben und Geräusche im Bild.','Ich stelle mir vor, wie ich mich morgen fühlen möchte.','Ich sehe mich ruhig sprechen.','Ich stelle mir eine sich öffnende Tür vor.','Ich darf das Bild langsam aufbauen.','Meine Zukunft darf mit einem kleinen Bild beginnen.'],
    'es-ES':['Imagino un lugar donde me siento segura.','Veo el siguiente paso con claridad.','Me imagino terminando una pequeña tarea.','Creo una imagen sencilla de mi objetivo.','Noto los colores y los sonidos de la imagen.','Imagino cómo quiero sentirme mañana.','Me veo hablando con calma.','Imagino una puerta que se abre.','Puedo construir la imagen poco a poco.','Mi futuro puede empezar con una imagen pequeña.'],
    'hr-HR':['Zamišljam mjesto na kojem se osjećam sigurno.','Jasno vidim sljedeći korak.','Zamišljam sebe kako završavam mali zadatak.','Stvaram jednostavnu sliku svog cilja.','Primjećujem boje i zvukove u slici.','Zamišljam kako se želim osjećati sutra.','Vidim sebe kako govorim mirno.','Zamišljam vrata koja se otvaraju.','Mogu graditi sliku malo po malo.','Moja budućnost može početi malom slikom.'],
    'fr-FR':['J’imagine un endroit où je me sens en sécurité.','Je vois clairement le prochain pas.','Je m’imagine terminer une petite tâche.','Je crée une image simple de mon objectif.','Je remarque les couleurs et les sons de l’image.','J’imagine comment je veux me sentir demain.','Je me vois parler calmement.','J’imagine une porte qui s’ouvre.','Je peux construire l’image petit à petit.','Mon avenir peut commencer par une petite image.']},
  meditation:{
    'de-DE':['Ich bemerke meinen Atem, ohne ihn zu verändern.','Ich lasse Gedanken kommen und gehen.','Ich spüre meine Füße auf dem Boden.','Ich kehre sanft zum Atem zurück.','Ich muss meinen Kopf nicht völlig leeren.','Ich beobachte den Moment ohne Urteil.','Mein Körper darf weich werden.','Ich bleibe für drei Atemzüge hier.','Ich höre die Geräusche um mich herum.','Auch eine Minute zählt.'],
    'es-ES':['Noto mi respiración sin cambiarla.','Dejo que los pensamientos vengan y se vayan.','Siento los pies en el suelo.','Vuelvo suavemente a la respiración.','No necesito vaciar completamente la mente.','Observo el momento sin juzgarlo.','Mi cuerpo puede aflojarse.','Me quedo aquí durante tres respiraciones.','Escucho los sonidos a mi alrededor.','Incluso un minuto cuenta.'],
    'hr-HR':['Primjećujem dah bez mijenjanja.','Puštam misli da dolaze i odlaze.','Osjećam stopala na podu.','Nježno se vraćam dahu.','Ne moram potpuno isprazniti um.','Promatram trenutak bez osuđivanja.','Moje tijelo može omekšati.','Ostajem ovdje tri udaha.','Slušam zvukove oko sebe.','I jedna minuta se računa.'],
    'fr-FR':['Je remarque ma respiration sans la modifier.','Je laisse les pensées venir et repartir.','Je sens mes pieds sur le sol.','Je reviens doucement à ma respiration.','Je n’ai pas besoin de vider complètement mon esprit.','J’observe le moment sans le juger.','Mon corps peut se relâcher.','Je reste ici pendant trois respirations.','J’écoute les sons autour de moi.','Même une minute compte.']},
  nature:{
    'de-DE':['Ich bemerke das Licht um mich herum.','Ich höre den Wind und die Vögel.','Ich spüre den Boden unter meinen Füßen.','Ein Baum muss sich nicht beeilen.','Ich atme die frische Luft ein.','Ich sehe eine Farbe in der Natur.','Wasser darf seinen eigenen Weg finden.','Der Himmel ist größer als dieser Moment.','Ich lasse meinen Blick in die Ferne gehen.','Die Natur erinnert mich an Veränderung.'],
    'es-ES':['Noto la luz a mi alrededor.','Escucho el viento y los pájaros.','Siento el suelo bajo mis pies.','Un árbol no necesita tener prisa.','Respiro el aire fresco.','Veo un color en la naturaleza.','El agua puede encontrar su propio camino.','El cielo es más grande que este momento.','Dejo que mi mirada vaya lejos.','La naturaleza me recuerda el cambio.'],
    'hr-HR':['Primjećujem svjetlo oko sebe.','Slušam vjetar i ptice.','Osjećam tlo pod nogama.','Stablo ne mora žuriti.','Udišem svježi zrak.','Vidim jednu boju u prirodi.','Voda može pronaći svoj put.','Nebo je veće od ovog trenutka.','Puštam pogled u daljinu.','Priroda me podsjeća na promjenu.'],
    'fr-FR':['Je remarque la lumière autour de moi.','J’écoute le vent et les oiseaux.','Je sens le sol sous mes pieds.','Un arbre n’a pas besoin de se dépêcher.','Je respire l’air frais.','Je vois une couleur dans la nature.','L’eau peut trouver son propre chemin.','Le ciel est plus grand que ce moment.','Je laisse mon regard aller au loin.','La nature me rappelle le changement.']}
};

function baseCode(code){ if(code==='es-AN') return 'es-ES'; if(code==='hr-DAL') return 'hr-HR'; return code; }
function dialect(text,code){
  if(code==='es-AN') return text.replaceAll('poco a poco','poquito a poquito').replaceAll('Paso a paso','Pasito a pasito');
  if(code==='hr-DAL') return text.replaceAll('Mogu ','Mogu ').replaceAll('Ne moram','Ne moran').replaceAll('polako','pomalo');
  return text;
}
function sourceSentences(category,code){
  const base=baseCode(code);
  if(base==='pt-PT') return category.exercises.slice(0,10).map(x=>[x.sentence,x.alternative]);
  if(base==='en-GB') return category.exercises.slice(0,10).map(x=>[x.english,x.alternativeEnglish]);
  const items=L[category.id]?.[base] || L.calm[base];
  return items.map(text=>[text,text]);
}
function build(category,learning,native){
  const a=sourceSentences(category,learning), b=sourceSentences(category,native);
  const ca=CONTEXTS[learning]||CONTEXTS[baseCode(learning)]||CONTEXTS['en-GB'];
  const cb=CONTEXTS[native]||CONTEXTS[baseCode(native)]||CONTEXTS['en-GB'];
  const out=[];
  for(let c=0;c<5;c++) for(let i=0;i<10;i++) out.push({
    sentence:dialect(ca[c]+a[i][0],learning),
    english:dialect(cb[c]+b[i][0],native),
    alternative:dialect(a[i][1],learning),
    alternativeEnglish:dialect(b[i][1],native)
  });
  return out;
}
export function getVoiceCategories(learningLanguage,nativeLanguage){
  return VOICE_CATEGORIES.map(category=>({...category,exercises:build(category,learningLanguage,nativeLanguage)}));
}
